[package]
name = 'cargo-tomlfmt'
version = '0.1.3'
authors = ['tbrand <taichiro0709@gmail.com>']
description = 'Formatting Cargo.toml'
homepage = 'https://github.com/tbrand/cargo-tomlfmt'
license = 'MIT'
repository = 'https://github.com/tbrand/cargo-tomlfmt'
edition = '2018'

[[bin]]
name = 'cargo-tomlfmt'
path = 'src/main.rs'

[dependencies]
clap = '2.32.0'
env_logger = '0.5.13'
failure = '0.1.3'
log = '0.4.6'
toml_edit = '0.1.3'
