[package]
name = 'cargo-tomlfmt'
version = '0.1.2'
authors = ['tbrand <taichiro0709@gmail.com>']
description = 'Formatting Cargo.toml'
homepage = 'https://github.com/tbrand/cargo-tomlfmt'
license = 'MIT'
repository = 'https://github.com/tbrand/cargo-tomlfmt'
edition = '2018'

[[bin]]
name = 'cargo-tomlfmt'
path = 'src/main.rs'

[dependencies]
cargo = '0.32.0'
clap = '2.32.0'
env_logger = '0.5.13'
failure = '0.1.3'
log = '0.4.6'
semver = '0.9.0'
serde = '1.0.82'
serde_derive = '1.0.82'
toml = '0.4.10'
